trigger:

- main
   
pool:
  vmImage: 'ubuntu-latest'
   

variables:
  imageName: 'sigo-regulatory-norms-api'
  DOCKER_BUILDKIT: 0
    
steps:

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Pago pelo Uso(600c3c04-d3aa-4551-8802-7abd773b35bb)'
    azureContainerRegistry: '{"loginServer":"sigoapp.azurecr.io", "id" : "/subscriptions/600c3c04-d3aa-4551-8802-7abd773b35bb/resourceGroups/sigo-resource-group/providers/Microsoft.ContainerRegistry/registries/sigoapp"}'
    dockerComposeFile: 'docker-compose.yml'
    action: 'Combine configuration'
    outputDockerComposeFile: '$(Build.StagingDirectory)/docker-compose.yml'
- task: Docker@2
  inputs:
    containerRegistry: 'Azure Container Registry'
    repository: 'sigo-regulatorynorms-api'
    command: 'buildAndPush'
    Dockerfile: 'SIGO.RegulatoryNorms.API/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest