trigger:
  paths:
    include:
      - 'SIGO.RegulatoryNorms.API/SIGO.Consulting.API/*'
      - 'SIGO.RegulatoryNorms.Application.Services/*'
      - 'SIGO.RegulatoryNorms.DataContracts/*'
      - 'SIGO.RegulatoryNorms.Infrastructure.CrossCutting/*'
  branches:
    include:
     - main
   
pool:
  vmImage: 'ubuntu-latest'
   

variables:
  imageName: 'sigo-regulatory-norms-api'
  DOCKER_BUILDKIT: 0
    
steps:

- task: Docker@2
  inputs:
    containerRegistry: 'Azure Container Registry'
    repository: 'sigo-regulatorynorms-api'
    command: 'buildAndPush'
    buildContext: '$(Build.SourcesDirectory)'
    Dockerfile: 'SIGO.RegulatoryNorms.API/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest